import './globals.css'
// import { Inter } from 'next/font/google'
import Link from 'next/link'
import Script from 'next/script'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <div className="w3-top">
          <div className="w3-bar w3-white w3-padding w3-card" style={{ 'letter-spacing': '4px' }}>
            <Link href="/" className="w3-bar-item w3-button">Gourmet au Catering</Link>
            <div className="w3-right w3-hide-small">
              <Link href="about" className="w3-bar-item w3-button">About</Link>
              <Link href="contact" className="w3-bar-item w3-button">Contact</Link>
            </div>
          </div>
        </div> */}
        {children}
      </body>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
    </html>
  )
}
